[program:datadog-agent-forwarder]
command=/opt/datadog-agent/bin/agent/agent run -p /opt/datadog-agent/run/agent.pid
stdout_logfile=NONE
stderr_logfile=NONE
startsecs=5
startretries=3
priority=998

[program:datadog-process-agent]
command=/opt/datadog-agent/embedded/bin/process-agent --config /etc/datadog-agent/datadog.yaml --sysprobe-config=/etc/datadog-agent/system-probe.yaml --pid=/opt/datadog-agent/run/process-agent.pid
stdout_logfile=NONE
stderr_logfile=NONE
startsecs=5
startretries=3
priority=998

[program:datadog-trace-agent]
command=/opt/datadog-agent/embedded/bin/trace-agent --config /etc/datadog-agent/datadog.yaml --pid /opt/datadog-agent/run/trace-agent.pid
stdout_logfile=NONE
stderr_logfile=NONE
startsecs=5
startretries=3
priority=998
autorestart=unexpected
exitcodes=0

[group:datadog-agent]
programs=datadog-agent-forwarder,datadog-process-agent,datadog-trace-agent